# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\"5\n\x0cTermRelation\x12\x0f\n\x07term_id\x18\x01 \x01(\x05\x12\x14\n\x0crelationship\x18\x02 \x01(\t\"m\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07keyword\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12$\n\rrelated_terms\x18\x05 \x03(\x0b\x32\r.TermRelation\"\x07\n\x05\x45mpty\"(\n\x10TermListResponse\x12\x14\n\x05terms\x18\x01 \x03(\x0b\x32\x05.Term\"\x1c\n\x0eGetTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x0cTermResponse\x12\x13\n\x04term\x18\x01 \x01(\x0b\x32\x05.Term2c\n\x0fGlossaryService\x12%\n\x08GetTerms\x12\x06.Empty\x1a\x11.TermListResponse\x12)\n\x07GetTerm\x12\x0f.GetTermRequest\x1a\r.TermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERMRELATION']._serialized_start=18
  _globals['_TERMRELATION']._serialized_end=71
  _globals['_TERM']._serialized_start=73
  _globals['_TERM']._serialized_end=182
  _globals['_EMPTY']._serialized_start=184
  _globals['_EMPTY']._serialized_end=191
  _globals['_TERMLISTRESPONSE']._serialized_start=193
  _globals['_TERMLISTRESPONSE']._serialized_end=233
  _globals['_GETTERMREQUEST']._serialized_start=235
  _globals['_GETTERMREQUEST']._serialized_end=263
  _globals['_TERMRESPONSE']._serialized_start=265
  _globals['_TERMRESPONSE']._serialized_end=300
  _globals['_GLOSSARYSERVICE']._serialized_start=302
  _globals['_GLOSSARYSERVICE']._serialized_end=401
# @@protoc_insertion_point(module_scope)