# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glossary_pb2 as glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Набор методов 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTerms = channel.unary_unary(
                '/GlossaryService/GetTerms',
                request_serializer=glossary__pb2.Empty.SerializeToString,
                response_deserializer=glossary__pb2.TermListResponse.FromString,
                _registered_method=True)
        self.GetTerm = channel.unary_unary(
                '/GlossaryService/GetTerm',
                request_serializer=glossary__pb2.GetTermRequest.SerializeToString,
                response_deserializer=glossary__pb2.TermResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Набор методов 
    """

    def GetTerms(self, request, context):
        """GET /api/terms
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """GET /api/terms/{id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerms,
                    request_deserializer=glossary__pb2.Empty.FromString,
                    response_serializer=glossary__pb2.TermListResponse.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=glossary__pb2.GetTermRequest.FromString,
                    response_serializer=glossary__pb2.TermResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Набор методов 
    """

    @staticmethod
    def GetTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GlossaryService/GetTerms',
            glossary__pb2.Empty.SerializeToString,
            glossary__pb2.TermListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GlossaryService/GetTerm',
            glossary__pb2.GetTermRequest.SerializeToString,
            glossary__pb2.TermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)